# Generated by Django 5.0.7 on 2024-07-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_ftpdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftpdetail',
            name='port',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
