# Generated by Django 5.0.7 on 2024-07-31 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0006_rename_inventory_vendorsourcefile_inventory_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('file_download', models.BooleanField(default=False)),
                ('file_upload', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_app.vendorsource')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
