# Generated by Django 5.0.7 on 2024-07-31 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0007_vendorlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorlogs',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
