# Generated by Django 5.0.7 on 2024-07-31 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0008_vendorlogs_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftpdetail',
            name='interval',
        ),
        migrations.AddField(
            model_name='vendorsource',
            name='interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
