# Generated by Django 5.0.7 on 2024-07-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0009_remove_ftpdetail_interval_vendorsource_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsource',
            name='unit',
            field=models.CharField(blank=True, choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], max_length=10, null=True),
        ),
    ]
